/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-settings-tab': RouteRecordInfo<'account-settings-tab', '/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'customers': RouteRecordInfo<'customers', '/customers', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'feedback-all': RouteRecordInfo<'feedback-all', '/feedback/all', Record<never, never>, Record<never, never>>,
    'feedback-list': RouteRecordInfo<'feedback-list', '/feedback/list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'materials-categories': RouteRecordInfo<'materials-categories', '/materials/categories', Record<never, never>, Record<never, never>>,
    'materials-list': RouteRecordInfo<'materials-list', '/materials/list', Record<never, never>, Record<never, never>>,
    'materials-movements': RouteRecordInfo<'materials-movements', '/materials/movements', Record<never, never>, Record<never, never>>,
    'materials-suppliers': RouteRecordInfo<'materials-suppliers', '/materials/suppliers', Record<never, never>, Record<never, never>>,
    'order-add-new-order': RouteRecordInfo<'order-add-new-order', '/order/AddNewOrder', Record<never, never>, Record<never, never>>,
    'orders': RouteRecordInfo<'orders', '/orders', Record<never, never>, Record<never, never>>,
    'roles-and-permissions': RouteRecordInfo<'roles-and-permissions', '/roles-and-permissions', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'user-view-id': RouteRecordInfo<'user-view-id', '/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
